import { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';
import { DEFAULT_REPORT_TEMPLATE, REPORT_VARIABLES, renderTemplate, type ReportKind, type TelegramTemplates } from '../../supabase/functions/client-reports/report-template';
const columnLabels={date:'Дата',campaigns:'Кампанії',leads:'Ліди',cpl:'CPL',cpm:'CPM',impressions:'Покази',cpc:'CPC',clicks:'Кліки',ctr:'CTR',spend:'Витрати',messages:'Переписки (необов’язково)',currency:'Валюта (необов’язково)'};
const defaultColumns={date:'A',campaigns:'B',leads:'C',cpl:'D',cpm:'E',impressions:'F',cpc:'G',clicks:'H',ctr:'I',spend:'J',messages:'',currency:''};
type Target={sheet_id:number;since:string;until:string;first_row:number;last_row:number;columns:typeof defaultColumns};
type Settings = { telegram_templates?:TelegramTemplates|null; sheet_target?:Target|null; enabled:boolean; daily:boolean; weekly:boolean; ad_account_id:string; spreadsheet_id:string; chat_id:string; bot_token?:string; has_bot?:boolean; start_date:string; last_success?:string; last_error?:string };
const day=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Warsaw',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const initial:Settings={enabled:false,daily:true,weekly:false,ad_account_id:'',spreadsheet_id:'',chat_id:'',start_date:day()};
export default function ClientReports({clientId,status}:{clientId:string;status:string}) {
 const [settings,setSettings]=useState<Settings>(initial);const [loaded,setLoaded]=useState(false);const [dirty,setDirty]=useState(false);
 const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');const [preview,setPreview]=useState('');
 const [tabs,setTabs]=useState<{id:number;title:string;rows:number}[]>([]);
 const [templateKind,setTemplateKind]=useState<ReportKind>('daily');
 const [testKind,setTestKind]=useState<ReportKind>('daily');
 const [date,setDate]=useState(()=>{const d=new Date(day()+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-1);return d.toISOString().slice(0,10);});
 const invoke=async(action:string)=>{
  if(!supabase)throw new Error('Звіти потребують підключення Supabase та входу в CRM.');
  const {data,error}=await supabase.functions.invoke('client-reports',{body:{action,client_id:clientId,settings,date,kind:testKind}});
  if(error){let detail='';try{detail=(await (error as any).context.json()).error;}catch{}throw new Error(detail || 'Функція звітів недоступна. Виконайте REPORTS_SETUP.md.');}
  if(data?.error)throw new Error(data.error);return data;
 };
 useEffect(()=>{let live=true;if(clientId){invoke('load').then(d=>{if(live){setSettings(d.settings || initial);setLoaded(true);}}).catch(e=>{if(live)setError(e.message);});}return()=>{live=false;};},[clientId]);
 const update=(key:keyof Settings,value:any)=>{setSettings(s=>({...s,[key]:value,...(key==='spreadsheet_id'?{sheet_target:null}:{})}));if(key==='spreadsheet_id')setTabs([]);setDirty(true);setPreview('');};
 const targetUpdate=(key:keyof Target,value:any)=>update('sheet_target',{...settings.sheet_target!,[key]:value});
 const template=settings.telegram_templates?.[templateKind]??DEFAULT_REPORT_TEMPLATE;
 const templateUpdate=(value:string)=>update('telegram_templates',{daily:DEFAULT_REPORT_TEMPLATE,weekly:DEFAULT_REPORT_TEMPLATE,...settings.telegram_templates,[templateKind]:value});
 let templateExample='';let templateError='';
 try{templateExample=renderTemplate(template,{name:'Приклад клієнта',period:templateKind==='daily'?'2026-10-08':'2026-10-05 — 2026-10-11',date_from:templateKind==='daily'?'2026-10-08':'2026-10-05',date_to:templateKind==='daily'?'2026-10-08':'2026-10-11',leads:'24',messages:'3',spend:'70,10 USD',cpl:'2,92 USD',impressions:'6748',clicks:'89',cpc:'0,79 USD',cpm:'10,39 USD',ctr:'1.32%',currency:'USD'});}catch(e:any){templateError=e.message;}
 const act=async(action:string)=>{setBusy(true);setError('');setMessage('');try{const d=await invoke(action);if(d.tabs)setTabs(d.tabs);if(d.settings){setSettings(d.settings);setDirty(false);}if(d.text)setPreview(d.text);setMessage(d.message || 'Готово');}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 if(!clientId)return <div className="report-panel full"><h3>Автоматичні звіти</h3><p>Спочатку збережіть нового клієнта, потім підключіть звіти.</p></div>;
 return <section className="report-panel full"><div className="report-heading"><div><h3>Автоматичні звіти</h3><p>Meta → Google Таблиця → Telegram. Ліди та валюта — з рекламного кабінету.</p></div><span className={'report-badge '+(status==='active'&&settings.enabled?'on':'')}>{status!=='active'?'Зупинено статусом клієнта':settings.enabled?'Увімкнено':'Вимкнено'}</span></div>
 {error&&<p role="alert" className="report-error">{error}</p>}
 {loaded&&<><div className="report-fields"><label>ID рекламного кабінету<input value={settings.ad_account_id} onChange={e=>update('ad_account_id',e.target.value)} placeholder="378174569508694"/></label><label>Google Таблиця<input value={settings.spreadsheet_id} onChange={e=>update('spreadsheet_id',e.target.value)} placeholder="https://docs.google.com/spreadsheets/d/…"/></label><label>Telegram chat ID<input value={settings.chat_id} onChange={e=>update('chat_id',e.target.value)} placeholder="-100…"/></label><label>Токен Telegram-бота<input type="password" autoComplete="new-password" value={settings.bot_token || ''} onChange={e=>update('bot_token',e.target.value)} placeholder={settings.has_bot?'Збережено •••• (залиште порожнім)':'Вставте токен бота'}/></label><label>Початок звітності<input type="date" value={settings.start_date} onChange={e=>update('start_date',e.target.value)}/></label></div>
 <div className="report-fields"><label>Куди записувати<select value={settings.sheet_target?'template':'default'} onChange={e=>update('sheet_target',e.target.value==='default'?null:{sheet_id:-1,since:settings.start_date,until:settings.start_date,first_row:2,last_row:32,columns:{...defaultColumns}})}><option value="default">Окремий аркуш «Meta — щодня»</option><option value="template">Мій наявний аркуш</option></select></label></div>
 {settings.sheet_target&&<><div className="report-buttons"><button type="button" className="secondary" disabled={busy} onClick={()=>act('tabs')}>Завантажити аркуші таблиці</button></div><div className="report-fields"><label>Аркуш<select value={settings.sheet_target.sheet_id} onChange={e=>targetUpdate('sheet_id',Number(e.target.value))}><option value={-1}>Оберіть аркуш</option>{!tabs.some(t=>t.id===settings.sheet_target!.sheet_id)&&settings.sheet_target.sheet_id>=0&&<option value={settings.sheet_target.sheet_id}>Збережений аркуш (ID {settings.sheet_target.sheet_id})</option>}{tabs.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><label>Період аркуша — від<input type="date" value={settings.sheet_target.since} onChange={e=>targetUpdate('since',e.target.value)}/></label><label>Період аркуша — до (включно)<input type="date" value={settings.sheet_target.until} onChange={e=>targetUpdate('until',e.target.value)}/></label><label>Перший рядок з датою<input type="number" min={1} value={settings.sheet_target.first_row} onChange={e=>targetUpdate('first_row',Number(e.target.value))}/></label><label>Останній рядок з датою<input type="number" min={1} value={settings.sheet_target.last_row} onChange={e=>targetUpdate('last_row',Number(e.target.value))}/></label></div><p className="report-hint">Колонки шаблону: впишіть літеру A–AZ. Порожня колонка даних не записується. Рядок «Загалом» не включайте в діапазон.</p><div className="report-fields">{(Object.keys(columnLabels) as (keyof typeof defaultColumns)[]).map(key=><label key={key}>{columnLabels[key]}<input maxLength={2} value={settings.sheet_target!.columns[key]} onChange={e=>targetUpdate('columns',{...settings.sheet_target!.columns,[key]:e.target.value.toUpperCase().trim()})}/></label>)}</div></>}
 <p className="report-hint">{settings.sheet_target?'Запис лише в порожні рядки обраного аркуша за датою, починаючи з «Початок звітності». Заповнені рядки та формули пропускаються. Валютні й відсоткові формати, кольори та розміри клітинок зберігаються. Переконайтеся, що валюта колонок відповідає кабінету Meta. Якщо залишаєте формули, очистіть відповідні літери колонок у CRM. Наступний період потребує вибору нового аркуша.':'Автозапис у вкладку «Meta — щодня». Оформлення вже створеної вкладки зберігається. Старі вкладки не змінюються.'} Усі кампанії та групи кабінету включені; переписки рахуються окремо від лідів.</p>
 <div className="telegram-editor"><h4>Текст Telegram-звіту</h4><p className="report-hint">Шаблони зберігаються окремо для цього клієнта. Змінюй текст, emoji та порядок рядків. Щоб приховати показник, видали його рядок.</p><div className="report-buttons telegram-tabs" role="group" aria-label="Шаблон звіту">{(['daily','weekly'] as const).map(kind=><button key={kind} type="button" className={templateKind===kind?'primary':'secondary'} aria-pressed={templateKind===kind} onClick={()=>setTemplateKind(kind)}>{kind==='daily'?'Щоденний':'Щотижневий'}</button>)}</div><label className="telegram-template-label">Шаблон повідомлення<textarea rows={13} maxLength={3000} value={template} onChange={e=>templateUpdate(e.target.value)} spellCheck={false}/></label><div className="telegram-editor-actions"><small>{template.length} / 3000</small><button type="button" className="secondary" onClick={()=>templateUpdate(DEFAULT_REPORT_TEMPLATE)}>Стандартний шаблон</button></div><details className="telegram-variables"><summary>Змінні для даних Meta</summary><p className="report-hint">Натисни змінну, щоб додати її в кінець шаблону. Суми вже містять валюту, CTR — знак %.</p><div className="report-buttons">{Object.entries(REPORT_VARIABLES).map(([key,label])=><button type="button" className="secondary" key={key} onClick={()=>templateUpdate(template+`{{${key}}}`)} title={label}>{label} <code>{`{{${key}}}`}</code></button>)}</div></details>{templateError?<p className="report-error">{templateError}</p>:<><p className="report-hint">Приклад вигляду — демонстраційні цифри. Фактичний звіт перевіряється кнопкою «Переглянути звіт» після збереження.</p><pre className="report-preview">{templateExample}</pre></>}</div>
 <div className="report-switches">{([['enabled','Автоматичні звіти'],['daily','Щодня о 08:10'],['weekly','Щопонеділка о 09:00']] as const).map(([key,label])=><label key={key}><input type="checkbox" checked={settings[key]} onChange={e=>update(key,e.target.checked)}/>{label}</label>)}</div>
 <p className="report-hint">Час Варшави. Щоденний звіт — за вчора, тижневий — за попередній понеділок–неділю. Місячні звіти додамо пізніше.</p>
 <div className="report-buttons"><button type="button" className="primary" disabled={busy || !dirty} onClick={()=>act('save')}>Зберегти звітність</button><button type="button" className="secondary" disabled={busy || dirty} onClick={()=>act('check')}>Перевірити підключення</button></div>
 <div className="report-test"><div className="report-fields"><label>Тип тестового звіту<select value={testKind} onChange={e=>{setTestKind(e.target.value as ReportKind);setPreview('');}}><option value="daily">Щоденний</option><option value="weekly">Щотижневий</option></select></label><label>{testKind==='daily'?'Дата тесту':'Дата у тижні надсилання'}<input type="date" value={date} onChange={e=>{setDate(e.target.value);setPreview('');}}/></label></div>{testKind==='weekly'&&<p className="report-hint">Звіт за понеділок–неділю тижня перед вибраною датою.</p>}<div className="report-buttons"><button type="button" className="secondary" disabled={busy || dirty} onClick={()=>act('preview')}>Переглянути звіт</button><button type="button" className="secondary" disabled={busy || dirty || status!=='active'} onClick={()=>act('sync')}>Записати в Google</button><button type="button" className="secondary" disabled={busy || dirty || status!=='active' || !settings.has_bot} onClick={()=>act('test')}>Google + тест у Telegram</button></div></div>
 {busy&&<p role="status">Виконується…</p>}{message&&<p role="status">{message}</p>}{preview&&<pre className="report-preview">{preview}</pre>}
 {settings.last_success&&<p className="report-hint">Останнє оновлення: {new Date(settings.last_success).toLocaleString('uk-UA',{timeZone:'Europe/Warsaw'})}</p>}{settings.last_error&&<p className="report-error">Остання помилка: {settings.last_error}</p>}
 </>}
 </section>;
}
