import {useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';
export default function ReportIntegrations(){
 const [meta,setMeta]=useState('');const [google,setGoogle]=useState('');const [state,setState]=useState<any>({});const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [note,setNote]=useState('');
 const call=async(action:string)=>{if(!supabase)throw new Error('Підключіть Supabase');const {data,error}=await supabase.functions.invoke('client-reports',{body:{action,settings:{meta_token:meta,google_json:google}}});if(error){let text='Розгорніть функцію звітів за REPORTS_SETUP.md';try{text=(await (error as any).context.json()).error || text;}catch{}throw new Error(text);}if(data.error)throw new Error(data.error);return data;};
 useEffect(()=>{let live=true;call('integration_load').then(s=>{if(live)setState(s);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[]);
 async function save(){setBusy(true);setError('');try{const s=await call('integration_save');setState(s);setMeta('');setGoogle('');setNote(s.message);const next=await call('integration_load');setState(next);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <section className="report-panel"><h3>Meta → Google → Telegram: звітність</h3><p>Одне підключення для всіх клієнтів. Налаштування таблиць і ботів — у картках клієнтів.</p>{error&&<p className="report-error">{error}</p>}<div className="report-fields"><label>Meta Access Token<input type="password" autoComplete="new-password" value={meta} onChange={e=>setMeta(e.target.value)} placeholder={state.has_meta?'Токен збережено ••••':'Вставте токен з ads_read'}/></label><label>Google: JSON сервісного акаунту<textarea rows={3} value={google} onChange={e=>setGoogle(e.target.value)} placeholder={state.has_google?'Доступ збережено. Для заміни вставте новий JSON.':'Вставте вміст JSON-файлу'}/></label></div><p className="report-hint">Google Таблиці потрібно відкрити для email сервісного акаунту з правом редагування.{state.google_email&&<><br/><strong>{state.google_email}</strong></>}</p><button className="primary" disabled={busy || (!meta&&!google)} onClick={save}>{busy?'Зберігаємо…':'Зберегти підключення'}</button>{note&&<p>{note}</p>}</section>;
}
